chore(commit-message-check.yml): Update commit-message-check.yml

diff --git a/.github/workflows/commit-message-check.yml b/.github/workflows/commit-message-check.yml
--- a/.github/workflows/commit-message-check.yml
+++ b/.github/workflows/commit-message-check.yml
@@ -18,13 +18,19 @@ jobs:
       - name: Validate commit messages
         run: |
           echo "⏳ Commit messages are being checked..."
+          INVALID_FOUND=0
           COMMITS=$(git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%s")
           echo "$COMMITS" | while read COMMIT_MSG; do
             echo "🔍 $COMMIT_MSG"
             echo "$COMMIT_MSG" | grep -Eq "^(feat|fix|chore|docs|style|refactor|test)(\(.+\))?: .{1,}" || {
               echo "❌ Incorrect commit message:"
               echo "$COMMIT_MSG"
-              echo "🧠 Correct format: <type>(<scope>): <message>"
-              exit 1
+              INVALID_FOUND=1
             }
           done
+          if [ $INVALID_FOUND -eq 1 ]; then
+            echo "🚫 Commit message validation failed."
+            exit 1
+          else
+            echo "✅ All commit messages are valid."
+          fi
